### ISSUE TITLE
Prototype pollution in expand.js

### ISSUE THREAD

**Issue by lelecolacola123** [SpoonX/homefront#21]
Prototype pollution vulnerability in function expand() in homefront/dist/lib/expand.js in homefront3.0.0.
The function expand() lead to Prototype pollution in line 31 and 34

https://cheatsheetseries.owasp.org/cheatsheets/Prototype_Pollution_Prevention_Cheat_Sheet.html

**Comment by RWOverdijk** [comment]
[Up to the people using the lib](https://github.com/SpoonX/homefront#security-warning)
